class Symbol:
    def __init__(self, symbol, right=None, left=None, bottom=None, top=None, is_arc = False, is_dash = False, is_double = False):
        self.symbol = symbol
        self.args = frozenset((right, left, bottom, top, is_arc, is_dash, is_double))

    def is_valid(self, right=None, left=None, bottom=None, top=None, is_arc = False, is_dash = False, is_double = False):
        return self.args == frozenset((right, left, bottom, top, is_arc, is_dash, is_double))
    def __str__(self):
        return str(self.symbol)

def select_symbol(right=None, left=None, bottom=None, top=None, is_arc = False, is_dash = False, is_double = False):
    for s in symbols:
        if s.is_valid(right, left, bottom, top, is_arc, is_dash, is_double):
            return str(s)
    return None

symbols = (Symbol('─'), # output from parser.py without latest comma
Symbol('━'),
Symbol('│'),
Symbol('┃'),
Symbol('┄', is_dash=True),
Symbol('┅', is_dash=True),
Symbol('┆', is_dash=True),
Symbol('┇', is_dash=True),
Symbol('┈', is_dash=True),
Symbol('┉', is_dash=True),
Symbol('┊', is_dash=True),
Symbol('┋', is_dash=True),
Symbol('┌', bottom=False, right=False),
Symbol('┍', bottom=False, right=True),
Symbol('┎', bottom=True, right=False),
Symbol('┏', bottom=True, right=True),
Symbol('┐', bottom=False, left=False),
Symbol('┑', bottom=False, left=True),
Symbol('┒', bottom=True, left=False),
Symbol('┓', bottom=True, left=True),
Symbol('└', top=False, right=False),
Symbol('┕', top=False, right=True),
Symbol('┖', top=True, right=False),
Symbol('┗', top=True, right=True),
Symbol('┘', top=False, left=False),
Symbol('┙', top=False, left=True),
Symbol('┚', top=True, left=False),
Symbol('┛', top=True, left=True),
Symbol('├', right=False),
Symbol('┝', right=True),
Symbol('┞', top=True, right=False, bottom=False),
Symbol('┟', bottom=True, right=False, top=False),
Symbol('┠', right=False),
Symbol('┡', bottom=False, right=True, top=True),
Symbol('┢', top=False, right=True, bottom=True),
Symbol('┣', right=True),
Symbol('┤', left=False),
Symbol('┥', left=True),
Symbol('┦', top=True, left=False, bottom=False),
Symbol('┧', bottom=True, top=False, left=False),
Symbol('┨', left=False),
Symbol('┩', bottom=False, top=True, left=True),
Symbol('┪', top=False, left=True, bottom=True),
Symbol('┫', left=True),
Symbol('┬', bottom=False),
Symbol('┭', left=True, right=False, bottom=False),
Symbol('┮', right=True, left=False, bottom=False),
Symbol('┯', bottom=False),
Symbol('┰', bottom=True),
Symbol('┱', right=False, left=True, bottom=True),
Symbol('┲', left=False, right=True, bottom=True),
Symbol('┳', bottom=True),
Symbol('┴', top=False),
Symbol('┵', left=True, right=False, bottom=False),
Symbol('┶', right=True, left=False, top=False),
Symbol('┷', top=False),
Symbol('┸', top=True),
Symbol('┹', right=False, left=True, top=True),
Symbol('┺', left=False, top=True, right=True),
Symbol('┻', top=True),
Symbol('┼'),
Symbol('┽', left=True, right=False),
Symbol('┾', right=True, left=False),
Symbol('┿'),
Symbol('╀', top=True, bottom=False),
Symbol('╁', bottom=True, top=False),
Symbol('╂'),
Symbol('╃', top=True, left=True, bottom=False, right=False),
Symbol('╄', top=True, right=True, bottom=False, left=False),
Symbol('╅', bottom=True, left=True, top=False, right=False),
Symbol('╆', bottom=True, right=True, top=False, left=False),
Symbol('╇', bottom=False, top=True),
Symbol('╈', top=False, bottom=True),
Symbol('╉', right=False, left=True),
Symbol('╊', left=False, right=True),
Symbol('╋'),
Symbol('╌', is_dash=True),
Symbol('╍', is_dash=True),
Symbol('╎', is_dash=True),
Symbol('╏', is_dash=True),
Symbol('═', is_double=True),
Symbol('║', is_double=True),
Symbol('╭', is_arc=True, bottom=False, right=False),
Symbol('╮', is_arc=True, bottom=False, left=False),
Symbol('╯', is_arc=True, top=False, left=False),
Symbol('╰', is_arc=True, top=False, right=False),
Symbol('╴'),
Symbol('╵', top=False),
Symbol('╶', right=False),
Symbol('╷', bottom=False),
Symbol('╸', left=True),
Symbol('╹', top=True),
Symbol('╺', right=True),
Symbol('╻', bottom=True),
Symbol('╼', left=False, right=True),
Symbol('╽', top=False, bottom=True),
Symbol('╾', left=True, right=False),
Symbol('╿', top=True, bottom=False))
